### PR TITLE
fix(chaosctl): using in-cluster or kubeconfig for port-forwarding ins…

### LINKED ISSUE #1404: port-forwarding in chaosctl does not play well with in-cluster kubernetes config
## Bug Report

As coments in https://github.com/chaos-mesh/chaos-mesh/pull/1392#issuecomment-759298307.

**What version of Kubernetes are you using?**

```
❯ k version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T08:38:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**

I want to run `chaosctl` in this pod: `chaos-controller-manager`.

- initial workload: `k apply -f https://raw.githubusercontent.com/paulbouwer/hello-kubernetes/master/yaml/hello-kubernetes.yaml`
- create an stresschaos: burn-cpu

```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: burn-cpu
spec:
  mode: one
  selector:
    labelSelectors:
      app: "hello-kubernetes"
  stressors: 
    cpu: 
      workers: 1
      load: 100
      options: ["--cpu 2", "--timeout 600", "--hdd 1"]
  duration: "30s"
  scheduler:
    cron: "@every 2m"
```
- `k cp <path-to-chaosctl> chaos-controller-manager-x-x:/chaosctl`
- `k -n chaos-testing exec -ti chaos-controller-manager-x-x -- /chaosctl debug stresschaos`

**What did you expect to see?**
`chaosctl` could print the detail of this stresschaos.

**What did you see instead?**

```
❯ k -n chaos-testing exec -ti chaos-controller-manager-d5464cb96-rmd27 -- /chaosctl debug stresschaos
[Chaos]: burn-cpu

[Pod]: hello-kubernetes-d67496c67-gkf4g

2021-01-14 08:02:28.337319 I | for hello-kubernetes-d67496c67-gkf4g: run command 'cat /proc/cgroups' failed with: forward ports failed: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
command terminated with exit code 1

```
**Output of chaosctl**

### PR DESCRIPTION
**Pull request by STRRL**
…tead of e2eframework context

Signed-off-by: STRRL <str_ruiling@outlook.com>

I think we do not need to cherry-pick this PR, because chaosctl is a debug **tool**, and we didn't release any version for `chaosctl` yet.

### What problem does this PR solve?

Fix #1404 

### What is changed and how does it work?
It implement another `RESTClientGetter` based on `genericclioptions.ConfigFlags`: overriding `ToRESTConfig() (*rest.Config, error)`, for return in-cluster config or config from "KUBECONFIG" or `~/.kube/config`

This PR also make chaosctl do not depends on `e2econfig` anymore, that's cloud cleanup any `init` func in kubernetes framework and ginkgo.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: pkg/chaosctl/common/common_rest_client_getter.go [hunk 1]
```diff
@@ -0,0 +1,52 @@
+// Copyright 2019 Chaos Mesh Authors.
```
Comment (fewdan) [inline pkg/chaosctl/common/common_rest_client_getter.go:1]: s/2019/2020/g

Comment (STRRL) [reply pkg/chaosctl/common/common_rest_client_getter.go]: fixed!

File: pkg/chaosctl/common/common_rest_client_getter.go [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+	if envvar := os.Getenv("KUBECONFIG"); len(envvar) > 0 {
+		kubeconfig = envvar
+	} else {
+		home, err := os.UserHomeDir()
+		if err != nil {
+			return nil, err
+		}
+		kubeconfig = filepath.Join(home, ".kube", "config")
+	}
+	return clientcmd.BuildConfigFromFlags("", kubeconfig)
```
Comment (WangXiangUSTC) [inline pkg/chaosctl/common/common_rest_client_getter.go:51]:
```suggestion
      kubeconfig := os.Getenv("KUBECONFIG")
	if  len(kubeconfig) == 0 {
		home, err := os.UserHomeDir()
		if err != nil {
			return nil, err
		}
		kubeconfig = filepath.Join(home, ".kube", "config")
	}
	return clientcmd.BuildConfigFromFlags("", kubeconfig)
```

Comment (WangXiangUSTC) [reply pkg/chaosctl/common/common_rest_client_getter.go:51]: it seems that this is more simple

**Review by WangXiangUSTC — COMMENTED** [review]
rest LGTM

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

File: pkg/chaosctl/common/common.go [hunk 3]
```diff
@@ -153,11 +151,15 @@ func MarshalChaos(s interface{}) (string, error) {
 
 // InitClientSet inits two different clients that would be used
 func InitClientSet() (*ClientSet, error) {
-	ctrlClient, err := client.New(config.GetConfigOrDie(), client.Options{Scheme: scheme})
+	restconfig, err := loadRestConfig()
```
Comment (cwen0) [inline pkg/chaosctl/common/common.go:154]: Why not using `config.GetConfigOrDie()` directly?

Comment (STRRL) [reply pkg/chaosctl/common/common.go:154]: When this PR just created, the refine about logging are not merged into master. The `logger` of controller-runtime is not configured. So `config.GetConfigOrDie()` will return without any output.

And `os.Exit(1)` makes `defer func(){}()` will not execute anymore.  I think it's not so good.🤪 I prefer to return an error then handle it at the upper layer, instead of exit directly.

I just realize that we could `config.GetConfig()`. It meets all my requirements.

**Comment by STRRL** [comment]
PTAL @cwen0 @WangXiangUSTC

**Review by fewdan — APPROVED** [review]
LGTM

File: pkg/chaosctl/common/common.go [hunk 4]
```diff
@@ -23,6 +23,8 @@ import (
 	"strings"
 	"time"
 
+	"sigs.k8s.io/controller-runtime/pkg/client/config"
```
Comment (WangXiangUSTC) [inline pkg/chaosctl/common/common.go:26]: need to format this import

Comment (cwen0) [reply pkg/chaosctl/common/common.go:26]: @STRRL PTAL

Comment (STRRL) [reply pkg/chaosctl/common/common.go]: Fixed manually. A little weird, I can't reformat these imports by `make check`.

**Review by fewdan — APPROVED** [review]
LGTM

**Review by WangXiangUSTC — APPROVED** [review]
LGTM
