### PR TITLE
fix: init TargetScope to prevent panic

### LINKED ISSUE #1209: chaos-dashboard: nil panic while view a network chaos experiment
## Bug Report

**What version of Kubernetes are you using?**

minikube on macos

```shell
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```
Chaos Mesh version v1.0.2

**What did you do?**

- `curl -sSL https://mirrors.chaos-mesh.org/v1.0.2/install.sh | bash`
- `k apply -f https://raw.githubusercontent.com/paulbouwer/hello-kubernetes/master/yaml/hello-kubernetes.yaml`
- create a networkchaos: mode all, namespace selector: default; target: mode all, namespace selector: default; cron:` @every 10m`, duration: `5m`
- click detail for this chaos experiment

**What did you expect to see?**
- detail page for this chaos

**What did you see instead?**
- forever loading page, and chaos-dashboard error logs:

```log
[GIN] 2020/11/23 - 14:03:10 | 200 |   34.954255ms |   192.168.105.1 | POST     "/api/experiments/new"
2020-11-23T14:03:10.135Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "networkchaos", "request": "default/just-a-network-chaos"}
[GIN] 2020/11/23 - 14:03:10 | 200 |      97.272µs |   192.168.105.1 | GET      "/api/experiments?namespace=&name=&kind=&status="
[GIN] 2020/11/23 - 14:03:10 | 200 |    1.232444ms |   192.168.105.1 | GET      "/api/events/dry"
2020-11-23T14:03:10.268Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "networkchaos", "request": "default/just-a-network-chaos"}
2020-11-23T14:03:10.294Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "networkchaos", "request": "default/just-a-network-chaos"}


2020/11/23 14:03:12 [Recovery] 2020/11/23 - 14:03:12 panic recovered:
GET /api/experiments/detail/1981112a-0fb5-4aea-8737-7076db7c8cee HTTP/1.1
Host: 10.108.229.57:2333
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7
Connection: keep-alive
Referer: http://10.108.229.57:2333/dashboard/experiments/1981112a-0fb5-4aea-8737-7076db7c8cee
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36


runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:212 (0x4516f9)
/usr/local/go/src/runtime/signal_unix.go:695 (0x451548)
/src/pkg/apiserver/experiment/experiment.go:540 (0x165ee24)
/src/pkg/apiserver/experiment/experiment.go:844 (0x16625c5)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x15963da)
/src/pkg/apiserver/utils/error.go:46 (0x1640d7f)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x15963da)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 (0x15a9adf)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x15963da)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 (0x15a8c10)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x15963da)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 (0x15a01b5)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 (0x159f8cc)
/usr/local/go/src/net/http/server.go:2836 (0x888cc2)
/usr/local/go/src/net/http/server.go:1924 (0x88457b)
/usr/local/go/src/runtime/asm_amd64.s:1373 (0x46b7d0)

[GIN] 2020/11/23 - 14:03:12 | 500 |     537.975µs |   192.168.105.1 | GET      "/api/experiments/detail/1981112a-0fb5-4aea-8737-7076db7c8cee"
2020-11-23T14:04:32.878Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "networkchaos", "request": "default/just-a-network-chaos"}
2020-11-23T14:04:32.890Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "networkchaos", "request": "default/just-a-network-chaos"}
[GIN] 2020/11/23 - 14:05:20 | 200 |     236.706µs |   192.168.105.1 | GET      "/api/experiments/state"
[GIN] 2020/11/23 - 14:05:20 | 200 |      86.751µs |   192.168.105.1 | GET      "/api/experiments?namespace=&name=&kind=&status="
[GIN] 2020/11/23 - 14:05:21 | 200 |      83.568µs |   192.168.105.1 | GET      "/api/common/chaos-available-namespaces"
[GIN] 2020/11/23 - 14:05:21 | 200 |     149.365µs |   192.168.105.1 | GET      "/api/experiments?namespace=&name=&kind=&status="
[GIN] 2020/11/23 - 14:05:21 | 200 |     568.893µs |   192.168.105.1 | GET      "/api/archives?namespace=&name=&kind="
2020-11-23T14:05:55.084Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "networkchaos", "request": "default/just-a-network-chaos"}
```

### PR DESCRIPTION
**Pull request by g1eny0ung**
Signed-off-by: Yue <g1enyy0ung@gmail.com>

### What problem does this PR solve?

Resolve #1209.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: pkg/apiserver/experiment/experiment.go [hunk 1]
```diff
@@ -537,6 +537,7 @@ func (s *Service) getNetworkChaosDetail(namespace string, name string) (Experime
 	}
 
 	if chaos.Spec.Target != nil {
+		info.Target.NetworkChaos.TargetScope = &core.ScopeInfo{}
```
Comment (cwen0) [inline pkg/apiserver/experiment/experiment.go:540]:
```
		info.Target.NetworkChaos.TargetScope = &core.ScopeInfo{
			SelectorInfo: core.SelectorInfo{
				NamespaceSelectors:  chaos.Spec.Target.TargetSelector.Namespaces,
				LabelSelectors:      chaos.Spec.Target.TargetSelector.LabelSelectors,
				AnnotationSelectors: chaos.Spec.Target.TargetSelector.AnnotationSelectors,
				FieldSelectors:      chaos.Spec.Target.TargetSelector.FieldSelectors,
				PhaseSelector:       chaos.Spec.Target.TargetSelector.PodPhaseSelectors,
			},
			Mode:  string(chaos.Spec.Target.TargetMode),
			Value: chaos.Spec.Target.TargetValue,
		}
```

Comment (g1eny0ung) [reply pkg/apiserver/experiment/experiment.go]: Got it. Already resolved.

**Review by cwen0 — APPROVED** [review]
LGTM
