### PR TITLE
fix!: use consistent units for netem delay/jitter

### LINKED ISSUE #4545: [Bug]: NetworkChaos delay times being passed as microseconds
### Chaos Mesh Version

v2.7.0

### Kubernetes Version

v1.28.13

### Describe the bug

The latency and jitter values on Delay experiments appear to be passed with incorrect magnitude to `tc`.
When I apply the NetworkChaos as defined below, I see no effect when I curl from the "frontend" to the "backend" pod (status is marked as injected).
When I increase the latency x1000 (ie `50,000ms`), then I get the expected 50ms increase in latency (measured with `time curl ...`, from 0.025s to 0.075s)

```
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-50ms
  namespace: chaos-mesh
spec:
  action: delay
  mode: all
  direction: to
  selector:
    namespaces:
      - default
    labelSelectors:
      tier: frontend
  delay:
    latency: "50ms"
    correlation: "0"
  target:
    mode: all
    selector:
      namespaces:
        - default
      labelSelectors:
        tier: backend
  duration: "5m"
```

The generated `tc` command in the chaos-daemon pod log is `tc qdisc add dev eth0 root netem delay 50000`, which doesn't have the desired effect.
If I run either of the below 2 commands manually, then I get a ~50ms delay as expected:
```
tc qdisc add dev eth0 root netem delay 50ms
tc qdisc add dev eth0 root netem delay 50000000
```

### To Reproduce

_No response_

### PR DESCRIPTION
**Pull request by andreyzher**
## What problem does this PR solve?

Fixes #4545 

## What's changed and how it works?

NetworkChaos latency and jitter values now preserve their format and are passed as strings with units to `netem delay`, instead of micro/nanoseconds.

`time.ParseDuration` is more permissive than `netem delay` in terms of the duration expressions it can parse, so I've applied a pattern-based validation on the corresponding CRD fields to keep inputs compatible.

## Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`

## Cherry-pick to release branches (optional)

> This PR should be cherry-picked to the following release branches:

- [ ] release-2.7
- [ ] release-2.6

### CHANGELOG

> Must include at least one of them.

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

### Tests

> Must include at least one of them.

- [x] Unit test
- [ ] E2E test
- [x] Manual test

### Side effects

- [ ] **Breaking backward compatibility**

## DCO

If you find the DCO check fails, please run commands like below to fix it:

> [!TIP]
> Depends on actual situations, for example, if the failed commit isn't the most recent
> one, you can use `git rebase -i HEAD~n` to re-signoff the commit.

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

File: pkg/chaosdaemon/types.go [hunk 1]
```diff
@@ -16,22 +16,34 @@
...
 
 import (
+	"time"
+
 	"github.com/vishvananda/netlink"
 
 	pb "github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb"
 )
 
 func ToNetlinkNetemAttrs(netem *pb.Netem) netlink.NetemQdiscAttrs {
```
Comment (andreyzher) [inline pkg/chaosdaemon/types.go:26]: This method doesn't appear to be referenced anywhere within the Chaos Mesh codebase - all former references seem to have been refactored out.

Comment (STRRL) [reply pkg/chaosdaemon/types.go:26]: we could safely remove this file so :)

Comment (andreyzher) [reply pkg/chaosdaemon/types.go]: Gone! Wasn't sure if it was retained for some sort of backwards compatibility, or just overlooked.
