### PR TITLE
fix: pod deletion caused twophase phase=Failed chaos.

### LINKED ISSUE #944: failed to apply action if pod container is not ready
## Bug Report

**What version of Kubernetes are you using?**
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**
As the example, I created the web-show pods and network-delay-test:

```
curl -sSL https://mirrors.chaos-mesh.org/v0.9.1/web-show/deploy.sh | sh
kubectl apply -f network-delay.yaml
```

and while I delete the pod by manually, and pause\resume the chaos:

```
kubectl annotate networkchaos web-show-network-delay experiment.chaos-mesh.org/pause=true
kubectl annotate networkchaos web-show-network-delay experiment.chaos-mesh.org/pause-
```

**What did you expect to see?**
The newly created pod should be applied the chaos rules.

**What did you see instead?**
The newly created pod didn't apply the chaos rules, what's more, I could see some error log inside controller-manager:

```
2020-09-23T07:36:50.295Z	INFO	controllers.NetworkChaos	Pausing	{"reconciler": "networkchaos", "action": "netem"}
2020-09-23T07:36:50.295Z	INFO	controllers.NetworkChaos	running modification on pod	{"reconciler": "networkchaos", "action": "netem", "key": {"namespace": "default", "name": "web-show-7b477b5c6-jmwfw"}, "modification": {"Steps":[{"Source":"default/web-show-network-delay"}]}}
2020-09-23T07:36:50.295Z	ERROR	controllers.NetworkChaos	error while finding pod	{"reconciler": "networkchaos", "action": "netem", "key": {"namespace": "default", "name": "web-show-7b477b5c6-jmwfw"}, "error": "Pod \"web-show-7b477b5c6-jmwfw\" not found"}
github.com/go-logr/zapr.(*zapLogger).Error
	/root/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/podnetworkmanager.(*PodNetworkManager).Commit.func1.1
	/src/controllers/networkchaos/podnetworkmanager/podnetworkmanager.go:86
k8s.io/client-go/util/retry.OnError.func1
	/root/go/pkg/mod/k8s.io/client-go@v0.17.0/util/retry/util.go:51
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff
	/root/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:292
k8s.io/client-go/util/retry.OnError
	/root/go/pkg/mod/k8s.io/client-go@v0.17.0/util/retry/util.go:50
k8s.io/client-go/util/retry.RetryOnConflict
	/root/go/pkg/mod/k8s.io/client-go@v0.17.0/util/retry/util.go:104
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/podnetworkmanager.(*PodNetworkManager).Commit.func1
	/src/controllers/networkchaos/podnetworkmanager/podnetworkmanager.go:73
golang.org/x/sync/errgroup.(*Group).Go.func1
	/root/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57
2020-09-23T07:36:50.298Z	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-chaos-mesh-org-v1alpha1-podnetworkchaos", "UID": "8be5fc8b-3be1-4977-b38c-eb6bd461d488", "kind": "chaos-mesh.org/v1alpha1, Kind=PodNetworkChaos", "resource": {"group":"chaos-mesh.org","version":"v1alpha1","resource":"podnetworkchaos"}}
2020-09-23T07:36:50.298Z	INFO	rawpodnetwork-resource	default	{"name": "web-show-7b477b5c6-jmwfw"}
2020-09-23T07:36:50.299Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-chaos-mesh-org-v1alpha1-podnetworkchaos", "UID": "8be5fc8b-3be1-4977-b38c-eb6bd461d488", "allowed": true, "result": {}, "resultError": "got runtime.Object without object metadata: &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:,Message:,Reason:,Details:nil,Code:200,}"}
2020-09-23T07:36:50.301Z	ERROR	controllers.NetworkChaos	error while creating podnetworkchaos	{"reconciler": "networkchaos", "action": "netem", "error": "PodNetworkChaos.chaos-mesh.org \"web-show-7b477b5c6-jmwfw\" is invalid: [metadata.ownerReferences.apiVersion: Invalid value: \"\": version must not be empty, metadata.ownerReferences.kind: Invalid value: \"\": kind must not be empty, metadata.ownerReferences.name: Invalid value: \"\": name must not be empty, metadata.ownerReferences.uid: Invalid value: \"\": uid must not be empty]"}
github.com/go-logr/zapr.(*zapLogger).Error
	/root/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/podnetworkmanager.(*PodNetworkManager).Commit.func1.1
	/src/controllers/networkchaos/podnetworkmanager/podnetworkmanager.go:102
k8s.io/client-go/util/retry.OnError.func1
	/root/go/pkg/mod/k8s.io/client-go@v0.17.0/util/retry/util.go:51
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff
	/root/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:292
k8s.io/client-go/util/retry.OnError
	/root/go/pkg/mod/k8s.io/client-go@v0.17.0/util/retry/util.go:50
k8s.io/client-go/util/retry.RetryOnConflict
	/root/go/pkg/mod/k8s.io/client-go@v0.17.0/util/retry/util.go:104
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/podnetworkmanager.(*PodNetworkManager).Commit.func1
	/src/controllers/networkchaos/podnetworkmanager/podnetworkmanager.go:73
golang.org/x/sync/errgroup.(*Group).Go.func1
	/root/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57
2020-09-23T07:36:50.301Z	ERROR	controllers.NetworkChaos	error while updating	{"reconciler": "networkchaos", "action": "netem", "error": "PodNetworkChaos.chaos-mesh.org \"web-show-7b477b5c6-jmwfw\" is invalid: [metadata.ownerReferences.apiVersion: Invalid value: \"\": version must not be empty, metadata.ownerReferences.kind: Invalid value: \"\": kind must not be empty, metadata.ownerReferences.name: Invalid value: \"\": name must not be empty, metadata.ownerReferences.uid: Invalid value: \"\": uid must not be empty]"}
github.com/go-logr/zapr.(*zapLogger).Error
	/root/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/podnetworkmanager.(*PodNetworkManager).Commit.func1
	/src/controllers/networkchaos/podnetworkmanager/podnetworkmanager.go:116
golang.org/x/sync/errgroup.(*Group).Go.func1
	/root/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57
2020-09-23T07:36:50.301Z	ERROR	controllers.NetworkChaos	fail to commit	{"reconciler": "networkchaos", "action": "netem", "error": "PodNetworkChaos.chaos-mesh.org \"web-show-7b477b5c6-jmwfw\" is invalid: [metadata.ownerReferences.apiVersion: Invalid value: \"\": version must not be empty, metadata.ownerReferences.kind: Invalid value: \"\": kind must not be empty, metadata.ownerReferences.name: Invalid value: \"\": name must not be empty, metadata.ownerReferences.uid: Invalid value: \"\": uid must not be empty]"}
github.com/go-logr/zapr.(*zapLogger).Error
	/root/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/trafficcontrol.(*Reconciler).cleanFinalizersAndRecover
	/src/controllers/networkchaos/trafficcontrol/types.go:209
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/trafficcontrol.(*Reconciler).Recover
	/src/controllers/networkchaos/trafficcontrol/types.go:182
github.com/chaos-mesh/chaos-mesh/controllers/twophase.(*Reconciler).Reconcile
	/src/controllers/twophase/types.go:103
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos.(*Reconciler).scheduleNetworkChaos
	/src/controllers/networkchaos/types.go:87
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos.(*Reconciler).Reconcile
	/src/controllers/networkchaos/types.go:51
github.com/chaos-mesh/chaos-mesh/controllers.(*NetworkChaosReconciler).Reconcile
	/src/controllers/networkchaos_controller.go:63
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/root/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/root/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/root/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:88
2020-09-23T07:36:50.301Z	INFO	controllers.NetworkChaos	After recovering	{"reconciler": "networkchaos", "action": "netem", "finalizers": []}
2020-09-23T07:36:50.301Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"NetworkChaos","namespace":"default","name":"web-show-network-delay","uid":"ed26e3e3-6e98-44dc-b8dc-b93b4fe0c09d","apiVersion":"chaos-mesh.org/v1alpha1","resourceVersion":"4930"}, "reason": "ChaosRecovered", "message": ""}
2020-09-23T07:36:50.305Z	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-chaos-mesh-org-v1alpha1-networkchaos", "UID": "de3d19cb-60ae-44f3-a986-2f1e905d3c90", "kind": "chaos-mesh.org/v1alpha1, Kind=NetworkChaos", "resource": {"group":"chaos-mesh.org","version":"v1alpha1","resource":"networkchaos"}}
2020-09-23T07:36:50.305Z	INFO	networkchaos-resource	default	{"name": "web-show-network-delay"}
2020-09-23T07:36:50.306Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-chaos-mesh-org-v1alpha1-networkchaos", "UID": "de3d19cb-60ae-44f3-a986-2f1e905d3c90", "allowed": true, "result": {}, "resultError": "got runtime.Object without object metadata: &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:,Message:,Reason:,Details:nil,Code:200,}"}
2020-09-23T07:36:50.308Z	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/validate-chaos-mesh-org-v1alpha1-networkchaos", "UID": "bbd53286-479b-4a68-9649-794e8cd8520d", "kind": "chaos-mesh.org/v1alpha1, Kind=NetworkChaos", "resource": {"group":"chaos-mesh.org","version":"v1alpha1","resource":"networkchaos"}}
2020-09-23T07:36:50.309Z	INFO	networkchaos-resource	validate update	{"name": "web-show-network-delay"}
2020-09-23T07:36:50.309Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/validate-chaos-mesh-org-v1alpha1-networkchaos", "UID": "bbd53286-479b-4a68-9649-794e8cd8520d", "allowed": true, "result": {}, "resultError": "got runtime.Object without object metadata: &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:,Message:,Reason:,Details:nil,Code:200,}"}
2020-09-23T07:36:50.313Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "networkchaos", "request": "default/web-show-network-delay"}
```

```
2020-09-23T07:36:53.180Z	INFO	controllers.NetworkChaos	running modification on pod	{"reconciler": "networkchaos", "action": "netem", "key": {"namespace": "default", "name": "web-show-7b477b5c6-s5mmm"}, "modification": {"Steps":[{"Source":"default/web-show-network-delay"},{"Item":{"type":"netem","delay":{"latency":"10ms","correlation":"0","jitter":"0ms"},"source":"default/web-show-network-delay"}}]}}
2020-09-23T07:36:53.182Z	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-chaos-mesh-org-v1alpha1-podnetworkchaos", "UID": "a433fd41-0d73-4436-a264-b897aa000d8e", "kind": "chaos-mesh.org/v1alpha1, Kind=PodNetworkChaos", "resource": {"group":"chaos-mesh.org","version":"v1alpha1","resource":"podnetworkchaos"}}
2020-09-23T07:36:53.182Z	INFO	rawpodnetwork-resource	default	{"name": "web-show-7b477b5c6-s5mmm"}
2020-09-23T07:36:53.183Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-chaos-mesh-org-v1alpha1-podnetworkchaos", "UID": "a433fd41-0d73-4436-a264-b897aa000d8e", "allowed": true, "result": {}, "resultError": "got runtime.Object without object metadata: &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:,Message:,Reason:,Details:nil,Code:200,}"}
2020-09-23T07:36:53.185Z	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/validate-chaos-mesh-org-v1alpha1-podnetworkchaos", "UID": "a6ff334f-816b-4a89-babf-c9064b56160e", "kind": "chaos-mesh.org/v1alpha1, Kind=PodNetworkChaos", "resource": {"group":"chaos-mesh.org","version":"v1alpha1","resource":"podnetworkchaos"}}
2020-09-23T07:36:53.185Z	INFO	rawpodnetwork-resource	validate create	{"name": "web-show-7b477b5c6-s5mmm"}
2020-09-23T07:36:53.185Z	INFO	handler.PodNetworkChaos	updating network chaos	{"pod": "default/web-show-7b477b5c6-s5mmm", "spec": {}}
2020-09-23T07:36:53.185Z	INFO	util	Creating client to chaos-daemon	{"node": "kind-control-plane"}
2020-09-23T07:36:53.188Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/validate-chaos-mesh-org-v1alpha1-podnetworkchaos", "UID": "a6ff334f-816b-4a89-babf-c9064b56160e", "allowed": false, "result": {}, "resultError": "got runtime.Object without object metadata: &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:,Message:,Reason:rpc error: code = Unknown desc = container id  is not a containerd container id,Details:nil,Code:403,}"}
2020-09-23T07:36:53.189Z	ERROR	controllers.NetworkChaos	error while creating podnetworkchaos	{"reconciler": "networkchaos", "action": "netem", "error": "admission webhook \"vpodnetworkchaos.kb.io\" denied the request: rpc error: code = Unknown desc = container id  is not a containerd container id"}
github.com/go-logr/zapr.(*zapLogger).Error
	/root/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/podnetworkmanager.(*PodNetworkManager).Commit.func1.1
	/src/controllers/networkchaos/podnetworkmanager/podnetworkmanager.go:102
k8s.io/client-go/util/retry.OnError.func1
	/root/go/pkg/mod/k8s.io/client-go@v0.17.0/util/retry/util.go:51
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff
	/root/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:292
k8s.io/client-go/util/retry.OnError
	/root/go/pkg/mod/k8s.io/client-go@v0.17.0/util/retry/util.go:50
k8s.io/client-go/util/retry.RetryOnConflict
	/root/go/pkg/mod/k8s.io/client-go@v0.17.0/util/retry/util.go:104
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/podnetworkmanager.(*PodNetworkManager).Commit.func1
	/src/controllers/networkchaos/podnetworkmanager/podnetworkmanager.go:73
golang.org/x/sync/errgroup.(*Group).Go.func1
	/root/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57
2020-09-23T07:36:53.189Z	ERROR	controllers.NetworkChaos	error while updating	{"reconciler": "networkchaos", "action": "netem", "error": "admission webhook \"vpodnetworkchaos.kb.io\" denied the request: rpc error: code = Unknown desc = container id  is not a containerd container id"}
github.com/go-logr/zapr.(*zapLogger).Error
	/root/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/podnetworkmanager.(*PodNetworkManager).Commit.func1
	/src/controllers/networkchaos/podnetworkmanager/podnetworkmanager.go:116
golang.org/x/sync/errgroup.(*Group).Go.func1
	/root/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57
2020-09-23T07:36:53.189Z	ERROR	controllers.NetworkChaos	fail to commit	{"reconciler": "networkchaos", "action": "netem", "error": "admission webhook \"vpodnetworkchaos.kb.io\" denied the request: rpc error: code = Unknown desc = container id  is not a containerd container id"}
github.com/go-logr/zapr.(*zapLogger).Error
	/root/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/trafficcontrol.(*Reconciler).Apply
	/src/controllers/networkchaos/trafficcontrol/types.go:149
github.com/chaos-mesh/chaos-mesh/controllers/twophase.applyAction
	/src/controllers/twophase/types.go:233
github.com/chaos-mesh/chaos-mesh/controllers/twophase.(*Reconciler).Reconcile
	/src/controllers/twophase/types.go:149
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos.(*Reconciler).scheduleNetworkChaos
	/src/controllers/networkchaos/types.go:87
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos.(*Reconciler).Reconcile
	/src/controllers/networkchaos/types.go:51
github.com/chaos-mesh/chaos-mesh/controllers.(*NetworkChaosReconciler).Reconcile
	/src/controllers/networkchaos_controller.go:63
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/root/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/root/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/root/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:88
2020-09-23T07:36:53.189Z	ERROR	controllers.NetworkChaos	failed to apply chaos action	{"reconciler": "networkchaos", "action": "netem", "error": "admission webhook \"vpodnetworkchaos.kb.io\" denied the request: rpc error: code = Unknown desc = container id  is not a containerd container id"}
github.com/go-logr/zapr.(*zapLogger).Error
	/root/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/chaos-mesh/chaos-mesh/controllers/twophase.applyAction
	/src/controllers/twophase/types.go:234
github.com/chaos-mesh/chaos-mesh/controllers/twophase.(*Reconciler).Reconcile
	/src/controllers/twophase/types.go:149
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos.(*Reconciler).scheduleNetworkChaos
	/src/controllers/networkchaos/types.go:87
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos.(*Reconciler).Reconcile
	/src/controllers/networkchaos/types.go:51
github.com/chaos-mesh/chaos-mesh/controllers.(*NetworkChaosReconciler).Reconcile
	/src/controllers/networkchaos_controller.go:63
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/root/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/root/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/root/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:88
2020-09-23T07:36:53.197Z	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-chaos-mesh-org-v1alpha1-networkchaos", "UID": "1fe2cfa7-2a1e-4a72-98e3-a8c2f6184522", "kind": "chaos-mesh.org/v1alpha1, Kind=NetworkChaos", "resource": {"group":"chaos-mesh.org","version":"v1alpha1","resource":"networkchaos"}}
```

The old one pod is `web-show-7b477b5c6-jmwfw`, and the new one is `web-show-7b477b5c6-s5mmm`.
BTW, the chaos controller would never fire another request to fix this, until the next schedule comes or fixed by manually(e.g. recreate it).

### PR DESCRIPTION
**Pull request by Colstuwjx**
### What problem does this PR solve?
Fixed #944 , addressed by [the issue comment](https://github.com/chaos-mesh/chaos-mesh/issues/944#issuecomment-697242197).

### What is changed and how does it work?
If networkchaos is Failed phase, it may need retry apply, and this PR help it come true!

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?
No

```release-note
NONE
```

### CODE REVIEW

File: controllers/twophase/types.go [hunk 1]
```diff
@@ -137,13 +138,14 @@ func (r *Reconciler) Reconcile(req ctrl.Request) (ctrl.Result, error) {
 		}
 		status.Experiment.Phase = v1alpha1.ExperimentPhaseWaiting
 		status.FailedMessage = emptyString
-	} else if status.Experiment.Phase == v1alpha1.ExperimentPhasePaused &&
+	} else if (status.Experiment.Phase == v1alpha1.ExperimentPhaseFailed ||
+		status.Experiment.Phase == v1alpha1.ExperimentPhasePaused) &&
```
Comment (YangKeao) [inline controllers/twophase/types.go:142]: wow! Here is the key to the problem :+1: !

File: controllers/networkchaos/podnetworkmanager/podnetworkmanager.go [hunk 2]
```diff
@@ -83,7 +93,15 @@ func (m *PodNetworkManager) Commit(ctx context.Context) error {
 					pod := v1.Pod{}
 					err = m.Client.Get(ctx, key, &pod)
 					if err != nil {
-						m.Log.Error(err, "error while finding pod", "key", key)
+						m.Log.Info("pod not found", "key", key, "error", err.Error())
+						err = ErrPodNotFound
+						return err
+					}
+
+					if pod.Status.Phase != v1.PodRunning {
```
Comment (Colstuwjx) [inline controllers/networkchaos/podnetworkmanager/podnetworkmanager.go:101]: These pod check code is nice-to-have thing, since we does the retry [below](https://github.com/chaos-mesh/chaos-mesh/pull/946/files#diff-6688ff79c2c81a4041a2754548d442c8R141), but I think networkchaos should not happens on invalid pods(not found, not running).

Anyway, feel free to ask me delete these code if we think it's useless.

**Review by YangKeao — APPROVED** [review]
LGTM

File: controllers/networkchaos/podnetworkmanager/podnetworkmanager.go [hunk 3]
```diff
@@ -83,7 +93,15 @@ func (m *PodNetworkManager) Commit(ctx context.Context) error {
 					pod := v1.Pod{}
 					err = m.Client.Get(ctx, key, &pod)
 					if err != nil {
-						m.Log.Error(err, "error while finding pod", "key", key)
+						m.Log.Info("pod not found", "key", key, "error", err.Error())
+						err = ErrPodNotFound
```
Comment (WangXiangUSTC) [inline controllers/networkchaos/podnetworkmanager/podnetworkmanager.go:97]: the error may not be `not found`, I think it's better to add an adjustment

File: controllers/networkchaos/partition/types.go [hunk 4]
```diff
@@ -196,6 +197,10 @@ func (r *Reconciler) Apply(ctx context.Context, req ctrl.Request, chaos v1alpha1
 
 	err = m.Commit(ctx)
 	if err != nil {
+		// if pod is not found or not ready, wait next time.
+		if err == podnetworkmanager.ErrPodNotFound || err == podnetworkmanager.ErrPodNotRunning {
+			return err
+		}
```
Comment (WangXiangUSTC) [inline controllers/networkchaos/partition/types.go:203]: why need these code, seems that  it will return err whatever the error type is

**Review by fewdan — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

File: controllers/networkchaos/trafficcontrol/types.go [hunk 5]
```diff
@@ -146,6 +146,10 @@ func (r *Reconciler) Apply(ctx context.Context, req ctrl.Request, chaos v1alpha1
 
 	err = m.Commit(ctx)
 	if err != nil {
+		// if pod is not found or not running, wait next time.
+		if err == podnetworkmanager.ErrPodNotFound || err == podnetworkmanager.ErrPodNotRunning {
+			return err
+		}
```
Comment (WangXiangUSTC) [inline controllers/networkchaos/trafficcontrol/types.go:152]: ditto

File: controllers/networkchaos/partition/types.go (hunk 4 above)
Comment (Colstuwjx) [reply controllers/networkchaos/partition/types.go:203]: The other errors would do `r.Log.Error(err, "fail to commit")`, I don't think we need the full-stack debug log if the pod is deleted or not running.

File: controllers/networkchaos/podnetworkmanager/podnetworkmanager.go (hunk 3 above)
Comment (zhouqiang-cl) [reply controllers/networkchaos/podnetworkmanager/podnetworkmanager.go:97]: make sense, I think later we can refine it

Comment (Colstuwjx) [reply controllers/networkchaos/podnetworkmanager/podnetworkmanager.go:97]: Yes, I agree with you.

File: controllers/networkchaos/partition/types.go (hunk 4 above)
Comment (WangXiangUSTC) [reply controllers/networkchaos/partition/types.go:203]:
```
if err != podnetworkmanager.ErrPodNotFound && err != podnetworkmanager.ErrPodNotRunning {
    r.Log.Error(err, "fail to commit")
}
return err
```

maybe this is better 😅

Comment (Colstuwjx) [reply controllers/networkchaos/partition/types.go:203]: Okay.
