### PR TITLE
fix: also enter pid namespace for 'cat /proc/mounts' 

### LINKED ISSUE #1305: chaosctl: failed to execute "cat /proc/mounts" when debugging iochaos
## Bug Report
chaosctl output:

```
[Pod]: hello-kubernetes-767d49787b-49pkp

2020-12-18 17:32:08.701919 I | for hello-kubernetes-767d49787b-49pkp: run command 'cat /proc/mounts' failed with: error in streaming remotecommand: command terminated with exit code 1, pod: chaos-daemon-852pk, command: /usr/local/bin/nsexec -m /proc/6901/ns/mnt -l -- cat /proc/mounts, std error: cat: /proc/mounts: No such file or directory

```

Because `/proc/mounts` is a symbolic link to `/proc/self/mounts`, so we should also enter PID namespace for procfs making this directory correctly.

### PR DESCRIPTION
**Pull request by Yiyiyimu**
Signed-off-by: yiyiyimu <wosoyoung@gmail.com>

### What problem does this PR solve?
Fix #1305

### What is changed and how does it work?
Also enter pid namespace for 'cat /proc/mounts' and skip process that not have file descriptors.
To make `ExecBypass` more flexible, use bpm to build cmd.

### Checklist

Tests

- [x] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by Yiyiyimu** [comment]
Hi @STRRL PTAL

File: pkg/chaosctl/common/exec.go [hunk 1]
```diff
@@ -75,29 +75,30 @@ func Exec(ctx context.Context, pod v1.Pod, cmd string, c *kubernetes.Clientset)
...
+		case "ps":
+			newCmd := fmt.Sprintf("/usr/local/bin/nsexec -m /proc/%s/ns/mnt -p /proc/%s/ns/pid -l -- %s", strconv.Itoa(pid), strconv.Itoa(pid), cmd)
+			return Exec(ctx, daemon, newCmd, c)
+		case "cat", "ls":
+			newCmd := fmt.Sprintf("/usr/local/bin/nsexec -m /proc/%s/ns/mnt -l -- %s", strconv.Itoa(pid), cmd)
+			return Exec(ctx, daemon, newCmd, c)
+		default:
+			return "", fmt.Errorf("command not supported for nsenter")
+		}
+	*/
```
Comment (STRRL) [inline pkg/chaosctl/common/exec.go:103]: Please remove these commented codes.

File: pkg/chaosctl/debug/iochaos/iochaos.go [hunk 2]
```diff
@@ -57,21 +58,23 @@ func Debug(ctx context.Context, chaos runtime.Object, c *cm.ClientSet, result *c
...
+		return fmt.Errorf("get pid from ps failed with: %s", err.Error())
+	}
 
 	for i := range pids {
 		cmd = fmt.Sprintf("ls -l /proc/%s/fd", pids[i])
 		out, err = cm.ExecBypass(ctx, pod, daemon, cmd, c.KubeCli)
-		if err != nil {
-			return fmt.Errorf("run command '%s' failed with: %s", cmd, err.Error())
+		if err == nil {
+			result.Items = append(result.Items, cm.ItemResult{Name: fmt.Sprintf("file discriptors of PID: %s, COMMAND: %s", pids[i], commands[i]), Value: string(out)})
```
Comment (STRRL) [inline pkg/chaosctl/debug/iochaos/iochaos.go:76]: If the error occurs, the user/developer could not receive any messages. It makes confusing while using and debugging.

Please print this error.

File: pkg/chaosctl/common/exec.go [hunk 3]
```diff
@@ -75,29 +75,30 @@ func Exec(ctx context.Context, pod v1.Pod, cmd string, c *kubernetes.Clientset)
 }
 
 // ExecBypass use chaos-daemon to enter namespace and execute command in target pod
-func ExecBypass(ctx context.Context, pod v1.Pod, daemon v1.Pod, cmd string, c *kubernetes.Clientset) (string, error) {
-	cmdSubSlice := strings.Fields(cmd)
-	if len(cmdSubSlice) == 0 {
-		return "", fmt.Errorf("command should not be empty")
-	}
+func ExecBypass(ctx context.Context, pod v1.Pod, daemon v1.Pod, cmd string, c *kubernetes.Clientset, nsTypes ...bpm.NsType) (string, error) {
```
Comment (STRRL) [inline pkg/chaosctl/common/exec.go:78]: Since we already use the bpm(which works with "nsexec"), I think it's OK to enter all common namespaces(mnt, pid, network, etc.) in `ExecByPass`. And then we could delete the last parameter ` nsTypes ...bpm.NsType`.

**Review by STRRL — CHANGES_REQUESTED** [review]
Basically LGTM, but here still some details that need re-considering.

PTAL @Yiyiyimu

File: pkg/chaosctl/common/exec.go (hunk 1 above)
Comment (Yiyiyimu) [reply pkg/chaosctl/common/exec.go]: My bad. Fixed thanks!

File: pkg/chaosctl/debug/iochaos/iochaos.go (hunk 2 above)
Comment (Yiyiyimu) [reply pkg/chaosctl/debug/iochaos/iochaos.go]: Since some process would not have its file descriptors, so I add this error handling method.

Changed to dealing with this certain error separately. Thanks!

File: pkg/chaosctl/common/exec.go (hunk 3 above)
Comment (Yiyiyimu) [reply pkg/chaosctl/common/exec.go]: Yeah I could not find side effects when we enter all possible namespaces. Fixed thx!

File: pkg/chaosctl/debug/iochaos/iochaos.go (hunk 2 above)
Comment (STRRL) [reply pkg/chaosctl/debug/iochaos/iochaos.go]: I think even "No such file or directory" also should be printed. 🤔 

I think "No such file or directory" will occur when some process was killed as soon as `ls /proc/%d/fd`, I think it's also a useful message.

Comment (Yiyiyimu) [reply pkg/chaosctl/debug/iochaos/iochaos.go]: Cool that indeed makes sense. Fixed

**Review by STRRL — APPROVED** [review]
LGTM

**Comment by STRRL** [comment]
Hi @YangKeao , PTAL

**Review by YangKeao — APPROVED** [review]
LGTM
