### PR TITLE
fix: workflow dashboard rendering for workflows that include a StatusCheck 

### LINKED ISSUE #4833: [Bug]: Workflows dashboard page not rendering
### Chaos Mesh Version

v2.8.1

### Kubernetes Version

v1.32.8

### Describe the bug

When trying to view a running workflow in the dashboard I created through a CRD, the page only shows 

```
Unexpected Application Error!
can't access property "map", n.nodes is null

Z4t@http://localhost:2333/assets/index-C3aKXiv6.js:755:101299
o@http://localhost:2333/assets/index-C3aKXiv6.js:755:103327
d@http://localhost:2333/assets/index-C3aKXiv6.js:755:103934
J4t@http://localhost:2333/assets/index-C3aKXiv6.js:755:104048
nAt/<@http://localhost:2333/assets/index-C3aKXiv6.js:755:105013
Vy@http://localhost:2333/assets/index-C3aKXiv6.js:48:84820
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99684
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:100431
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:100431
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:100431
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:100431
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:100431
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:100431
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99707
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:100431
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:100431
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:100431
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:100431
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:100431
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:100431
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:100431
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:100431
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99707
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:100431
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:100431
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:100431
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:100431
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:100431
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99666
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:100431
pf@http://localhost:2333/assets/index-C3aKXiv6.js:48:99570
K3@http://localhost:2333/assets/index-C3aKXiv6.js:48:99732
hO@http://localhost:2333/assets/index-C3aKXiv6.js:48:112576
xx@http://localhost:2333/assets/index-C3aKXiv6.js:48:112351
dO@http://localhost:2333/assets/index-C3aKXiv6.js:48:112122
Zy@http://localhost:2333/assets/index-C3aKXiv6.js:48:110032
nO@http://localhost:2333/assets/index-C3aKXiv6.js:48:105124
tO@http://localhost:2333/assets/index-C3aKXiv6.js:48:104771
yO@http://localhost:2333/assets/index-C3aKXiv6.js:48:115961
eb@http://localhost:2333/assets/index-C3aKXiv6.js:48:114518
tb@http://localhost:2333/assets/index-C3aKXiv6.js:48:114791
vTe/ES/<@http://localhost:2333/assets/index-C3aKXiv6.js:48:116019

💿 Hey developer 👋

You can provide a way better UX than this when your app throws errors by providing your own ErrorBoundary or errorElement prop on your route.
```

### To Reproduce

Create a simple workflow via the CRD and try to view it at `http://localhost:2333/#/workflows/130b0d15-0ad1-459b-av48-f22d2251637a` for instance.

### PR DESCRIPTION
**Pull request by imbstack**
## What problem does this PR solve?

When a workflow is created that includes a StatusCheck, the dashboard page for viewing a workflow crashes. 

Fixes #4833 

## What's changed and how does it work?

This PR first fixes the crash by checking that a topology not only is not null but also includes nodes before trying to render it. It then gets a topology to actually render by adding StatusCheck as a type that it knows about. Finally I commit the auto-generated changes to the swagger spec that `make check` added.

I generated an image from this and run it in my deployment where it appears to work!

## Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`

## Cherry-pick to release branches (optional)

> This PR should be cherry-picked to the following release branches:

- [ ] release-2.7
- [ ] release-2.6

### CHANGELOG

> Must include at least one of them.

- [ ] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog" (I don't have permissions to add labels but I don't believe this needs a changelog)

### Tests

> Must include at least one of them.

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test

### Side effects

- [ ] **Breaking backward compatibility**

## DCO

If you find the DCO check fails, please run commands like below to fix it:

> [!TIP]
> Depends on actual situations, for example, if the failed commit isn't the most recent
> one, you can use `git rebase -i HEAD~n` to re-signoff the commit.

```shell
git commit --amend --signoff
git push --force
```

(I figure you want to sign off on these commits yourselves but if it is _my_ signoff you want then I'm happy to do the above!)

### CODE REVIEW

File: ui/app/src/components/ObjectConfiguration/Node.tsx [hunk 1]
```diff
@@ -147,7 +149,9 @@ const NodeConfiguration: ReactFCWithChildren<NodeConfigurationProps> = ({ templa
   const rendered = () => {
     switch (t.templateType) {
       case 'Suspend':
-        return <Suspend template={t} />
+      case 'StatusCheck':
+      case 'Schedule':
+        return <SimpleNode template={t} />
```
Comment (g1eny0ung) [inline ui/app/src/components/ObjectConfiguration/Node.tsx:154]: In this place, a better approach is to create different components for different templates. I'll create an issue to track this problem.
